version: "3"
services:
  server:
    build: server/
    command: python ./server.py
    deploy:
      replicas: 2
    environment:
      - MYSQL_ROOT_PASSWORD="Str0ngPwd!"
  database:
    image: percona:8.0.28-19
    environment:
      - MYSQL_ROOT_PASSWORD="Str0ngPwd!"
  nginx:
    image: nginx:1.22.0
    ports:
      - 8080:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


